In [1]:
%load_ext autoreload
%autoreload 2


import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

from cellmates.data.sample import Sample
from cellmates.data.dataset import CellMatesDataset
from cellmates.data.stubs import (
    generate_dataset_for_n_cells_test, 
    generate_dataset_for_cell_type, 
    generate_dataset_for_distances
)


In [2]:
sample = Sample(
    cell_types=[1,2,3], 
    distances=torch.zeros((3,3)), 
    responder_cell_type=1, 
    is_dividing=False
)
sample


        responder_cell_type: 1
        is_dividing: False
        cell_types: [1, 2, 3]
        distances: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
        

# Test datasets:

In [3]:
generate_dataset_for_n_cells_test()
generate_dataset_for_cell_type()
generate_dataset_for_distances()

In [4]:
area = (3.14*(140**2))


In [5]:
H,L,K = 2,3,4

E_HLL = torch.randn((H,L,L))

V1_LK = torch.randn((L,K))
V2_LK = torch.randn((L,K))

V_HLK = torch.stack([V1_LK,V2_LK])

# using einsum
V_LHK = V_HLK.permute(1,0,2)
Z_LHK = torch.einsum("HLX,XHK->LHK", E_HLL, V_LHK)

# using straightforward:
Z_HLK_sf = torch.matmul(E_HLL, V_HLK)
Z_HLK_sf = Z_HLK_sf.view(L,H,K)

In [6]:
Z_LHK

tensor([[[-1.9680, -3.2961, -0.5398,  2.1047],
         [ 1.5051,  2.8094, -5.9635, -0.2780]],

        [[-2.1689,  2.8505, -0.7173,  1.2626],
         [-0.9921, -2.0040,  4.3604,  0.0680]],

        [[-2.6026, -1.3980, -0.9697,  2.8767],
         [-0.4299,  0.8791, -2.5356,  0.5676]]])

In [7]:
Z_HLK_sf

tensor([[[-1.9680, -3.2961, -0.5398,  2.1047],
         [-2.1689,  2.8505, -0.7173,  1.2626]],

        [[-2.6026, -1.3980, -0.9697,  2.8767],
         [ 1.5051,  2.8094, -5.9635, -0.2780]],

        [[-0.9921, -2.0040,  4.3604,  0.0680],
         [-0.4299,  0.8791, -2.5356,  0.5676]]])

In [14]:
from cellmates.model.transformer import SpatialMultiHeadAttention

In [17]:
H,L,K = 2,3,4
D = H*K

smh = SpatialMultiHeadAttention(D,H,K,'cpu')

In [20]:
B = 16
x = torch.randn((B,L,D))
smh(x).shape

torch.Size([16, 3, 8])